### ISSUE TITLE
Mashlib recipe : no login from an android browser

### ISSUE THREAD

**Issue by bourgeoa** [CommunitySolidServer/Recipes#27]
Fail to login on a CSS server with mashlib from an android phone and an MI 5 tablet (android) : 

- login popup and consent appear correctly. then just no login with no error message
- tested https://solidcommunity.net:3000/ (subdomain server) and also on my own test servers (subdomain and suffix)
- tested with chrome and brave browser
- no issue on a PC

There are no problems to login with an android browser to a NSS server

**Comment by joachimvh** [comment]
It is not clear yet to me exactly what is failing. Does the CSS not redirect back to the client after pressing the button on the consent page? Or does the server not return access tokens when requested afterwards?

**Comment by bourgeoa** [comment]
- CSS does redirect to the client after pressing the consent button
- the client seems to not receive access tokens. The client is in the same state as before pressing login

**Comment by joachimvh** [comment]
It is hard to say immediately what the probably might be since multiple pieces of software are involved here. If the redirect back to the client did happen that means the solid authn client received something. Question is if there is something missing in the response, if there was an error, or if there is an issue with how the authn client interprets the data.

**Comment by bourgeoa** [comment]
resolved using private navigation. Then everything is back again.
I suppose this relates to cleaning the browser cache.
